// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1NcedIvDX4MApD3XVsAPmf-wmHDckbYM',
    appId: '1:489857739807:web:cc8d2f9115491142d1792a',
    messagingSenderId: '489857739807',
    projectId: 'flutterdemoapp-50dc1',
    authDomain: 'flutterdemoapp-50dc1.firebaseapp.com',
    storageBucket: 'flutterdemoapp-50dc1.appspot.com',
    measurementId: 'G-49GF76465W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXoBYnzD_V3dWmHw788YGuJFXkZDRa_iw',
    appId: '1:489857739807:android:40fada5df8438389d1792a',
    messagingSenderId: '489857739807',
    projectId: 'flutterdemoapp-50dc1',
    storageBucket: 'flutterdemoapp-50dc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbKvc6pC7Q3LIYOnNZQOJW4f-bZEZxcRI',
    appId: '1:489857739807:ios:763b19d5cbc1c10ad1792a',
    messagingSenderId: '489857739807',
    projectId: 'flutterdemoapp-50dc1',
    storageBucket: 'flutterdemoapp-50dc1.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbKvc6pC7Q3LIYOnNZQOJW4f-bZEZxcRI',
    appId: '1:489857739807:ios:763b19d5cbc1c10ad1792a',
    messagingSenderId: '489857739807',
    projectId: 'flutterdemoapp-50dc1',
    storageBucket: 'flutterdemoapp-50dc1.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1NcedIvDX4MApD3XVsAPmf-wmHDckbYM',
    appId: '1:489857739807:web:afb692cd326f59d0d1792a',
    messagingSenderId: '489857739807',
    projectId: 'flutterdemoapp-50dc1',
    authDomain: 'flutterdemoapp-50dc1.firebaseapp.com',
    storageBucket: 'flutterdemoapp-50dc1.appspot.com',
    measurementId: 'G-K9B9SNPVST',
  );
}
